### ISSUE TITLE
Argument list too long -:1.1: Document is empty

### ISSUE THREAD

**Issue by GadgetGeekNI** [alectrona/git4jamfpro#12]
Hi all, I seem to be doing something wrong... 
I'm pulling down a script and xml, renaming one of the parameters in the xml and pushing back up and getting the error in the title. 

This is my xml, no formatting issues. Not sure where to go from here.

```
<?xml version="1.0" encoding="UTF-8"?>
<script>
  <name>setupYourMac.sh</name>
  <category>Enrollment</category>
  <info/>
  <notes/>
  <priority>After</priority>
  <parameters>
    <parameter4>scriptLog</parameter4>
    <parameter5>debugMode</parameter5>
    <parameter6>welcomeDialog</parameter6>
    <parameter7>completedActionOption</parameter7>
    <parameter8>requiredMinimumBuild</parameter8>
    <parameter9>outdatedOsAction</parameter9>
    <parameter10>webhookURL</parameter10>
    <parameter11>presetConfiguration</parameter11>
  </parameters>
  <os_requirements/>
</script>
```

I saw a different issue similar to this but I noticed I already have that hotfix as I just started using git4jamfpro in the past week or so.

**Comment by ryangball** [comment]
That XML worked fine for me. I assume the script is just a vanilla setupyourmac script?

**Comment by GadgetGeekNI** [comment]
That's correct. I'm not exactly sure what's going wrong with it. The script itself runs fine.

**Comment by GadgetGeekNI** [comment]
If it helps. 

This is the whole error message..

`./git4jamfpro.sh: line 94: /usr/bin/xmlstarlet: Argument list too long
-:1.1: Document is empty
^
Failed to encode the script xml record and script contents properly.`

Do you think it could be caused by the script itself in that case?

**Comment by ryangball** [comment]
Yes, I just tested with the script contents and received the same error. I have a thought. Is this what you are getting in your CI/CD pipeline or locally?

**Comment by GadgetGeekNI** [comment]
That's in the Bitbucket Pipeline!

Mine is just using the basic example but for reference, below.

```
image: atlassian/default-image:3
definitions:
  services:
    docker:
      memory: 4096
  steps:
    - step: &PushChangesToJamfPro
        name: 'Pushing Changes to Jamf Pro'
        clone:
          depth: 2
        script:
          - apt-get update && apt-get install libxml2-utils xmlstarlet -y
          - chmod +x ./git4jamfpro.sh
          - ./git4jamfpro.sh --url "$JAMF_PRO_URL" --username "$API_USER" --password "$API_PASS" --push-changes-to-jamf-pro --backup-updated
        artifacts:
          - backups/**

pipelines:
  default:
    - step:
        name: Default pipeline executed
        script:
          - echo "No action taken outside of Development/Production branch."
  branches:
    development:
      - step: *PushChangesToJamfPro
    production:
      - step: *PushChangesToJamfPro
```
